### ISSUE TITLE
How to prevent side effects from triggering when replaying routing actions?

### ISSUE THREAD

**Issue by rybon** [rackt/redux-simple-router#100]
When replaying a sequence of routing actions (basically what this repo enables Redux DevTools to do), how do you prevent side effects (such as data fetching triggering additional dispatches) from happening? According to the React Router 1.0 docs (https://github.com/rackt/react-router/blob/master/docs/guides/advanced/ComponentLifecycle.md), component life cycle methods are a good place to trigger side effects, such as data fetching using the URL params. But won't that clobber the sequence of actions you're replaying? In other words, won't that break the idempotence of restoring the UI to its current state? If dispatching routing actions trigger additional dispatches through side effects, the sequence of actions will be interrupted by unexpected additional actions, which makes replaying the sequence unpredictable. How do I solve this? Or am I missing something here?

I asked more or less the same question in https://github.com/rackt/redux-router/issues/207 and https://github.com/rackt/react-router/issues/2045.

**Comment by kjbekkelund** [comment]
Hi @rybon. I've been thinking about this, but have no good answers. I haven't found this to be a problem in my apps, but I see the point about idempotence.

As this isn't an issue with redux-simple-router itself (more of a general "pattern" with react-router + redux), I'll close this.

If you find a good solution to this, let us know, and we might add something to the readme about it.
