### ISSUE TITLE
Causes reactRouter onUpdate to be double invoked

### ISSUE THREAD

**Issue by tomatau** [rackt/redux-simple-router#108]
When redux-simple-router is setup and a path is updated through a Link or IndexLink from react router, the Router.onUpdate method is double invoked.

If pushPath or updatePath is used, the onUpdate behaves normally.

Here's a branch where it's happening for me
onUpdate handler:
https://github.com/tomatau/breko-hub/blob/versionUpdates/src/app/entry.js#L33

integration:
https://github.com/tomatau/breko-hub/blob/versionUpdates/src/app/state/store.js#L23

navigation:
https://github.com/tomatau/breko-hub/blob/versionUpdates/src/app/components/containers/HeadNavigation.js#L23

**Comment by kjbekkelund** [comment]
Thanks, @tomatau. Seeing the same in my app when I add a `console.log` to `onUpdate`. I'll take a look and see what I find.

**Comment by kjbekkelund** [comment]
I've got a failing tests, looking for a solution that doesn't break other stuff.

**Comment by kjbekkelund** [comment]
@tomatau I found a solution and created a PR. I'll have to think a bit more on it as I'm not entirely sure about the implementation, but hopefully we should have a fix soon.

**Comment by kjbekkelund** [comment]
I'm closing this as we're tracking it in #109

**Comment by tomatau** [comment]
Thanks for addressing this so quickly

**Comment by kjbekkelund** [comment]
I re-opened it. #109 already solves a double update, but there might be another problem here. Will look at it tomorrow.

**Comment by kjbekkelund** [comment]
@tomatau Maybe you could try out #129 and see if it helps with the double `onUpdate`?

**Comment by tomatau** [comment]
When navigating with pushPath, it dispatches `@@router/UPDATE_PATH ` twice, once with `state: false, replace: false` and the second with `state: null, replace: true`.

When navigating with a normal Link (history), the `@@router/UPDATE_PATH` is only dispatched once, but the Router.onUpdate is still double invoked.
