### ISSUE TITLE
Redux DevTools issue (reapplying state)

### ISSUE THREAD

**Issue by fkrauthan** [rackt/redux-simple-router#113]
It looks like there is still an issue if I go thru the list of state changes and disable a state everything is working fine (route is getting updated). But as soon as I enable that state again it looks like the browser url is not changing again. Let me know if you guys need more information.

**Comment by fkrauthan** [comment]
It looks like it is not always happening. Only after a while when I play around with enabling and disabling different navigation states (e.g. navigating back and forth between two pages and then click on the DevTools to disable states and reenabling them.)

**Comment by kjbekkelund** [comment]
Hm, interesting. I don't use the DevTools much, so I haven't seen this happen. Let me know if you find a reproducible way to make it fail. I'm probably going to focus on #108 and #109 first.

**Comment by timdorr** [comment]
I think this is obsoleted by 2.0, but let me know if it's still happening and I can re-open.
