### ISSUE TITLE
history.goBack()

### ISSUE THREAD

**Issue by acnovais** [rackt/redux-simple-router#126]
Hey Guys,

I am using a `MemoryHistory` and I would like to execute a `goBack()` with the router. Do you have any suggestions on how to do this?

Thanks

**Comment by kjbekkelund** [comment]
Are you seeing bugs or problems with redux-simple-router? Not sure I understand what you need

**Comment by kjbekkelund** [comment]
Ah, now with #127 I think I understand what you mean. I would suggest just using `history` directly.

**Comment by jlongster** [comment]
Closing as a dupe of #127
