### ISSUE TITLE
Fully Support Navigation Primitives of History API

### ISSUE THREAD

**Issue by mjrussell** [rackt/redux-simple-router#127]
PushPath and ReplacePath cover most of the general cases but it would be really nice to have action creators from `redux-simple-router` for the rest of the methods on the history api:

https://github.com/rackt/history/blob/master/docs/GettingStarted.md#navigation

Mainly `goForward()` and `goBack()`

This might be related to #126 but I couldn't really tell from the original post

**Comment by kjbekkelund** [comment]
Aaah, now I understood #126, thanks :) Are there any problems using `history` directly for this? I have never needed these APIs in my own apps, so not entirely sure.

**Comment by mjrussell** [comment]
I don't see a problem in using the history API directly (or proxying to it in some way), but how would you recommend passing it (or a proxy) down via Redux to connected-components? I guess wherever you create the history object could export the history object and in an action creator you could make calls there. Ideally these are things you can include in `mapDispatchToProps` argument of the connect function.

**Comment by mjrussell** [comment]
Maybe the "best" way to do this would be to use a middleware approach for history like `redux-router` does: https://github.com/acdlite/redux-router/blob/master/src/historyMiddleware.js

I understand `redux-simple-router` is trying to avoid some of the pitfalls of `redux-router` in terms of scope but this seems like a possibly more natural way to proxy requests to the history API.

**Comment by jlongster** [comment]
Personally I think middleware should only be transforming actions into other actions, nothing else. It shouldn't actually have any side effects.

But I think this issue is valid, we can just add 3 more actions for `go`, `goBack`, and `goForward`. It's a small API so it's easy to just manually implement these. I'm not exactly sure how yet, but I'm going to look at other issues first because some of them include refactory how we interact with `history`.

**Comment by acnovais** [comment]
Awesome!
Looking forward for this

**Comment by adiachenko** [comment]
+1 for this. For example, I have routes that might display as a modal depending on the context (see [pinterest example](https://github.com/rackt/react-router/tree/master/examples/pinterest) in react-router repo). When closing this modal, I want to contextually change route back to previous one, but I can't do this with pushPath. Using history API directly is fine, but this introduces inconsistency in my code which eliminates the entire purpose of using redux-simple-router.

**Comment by timdorr** [comment]
Added in 2.0 :smile:
