### ISSUE TITLE
multiple routerWillLeave triggers

### ISSUE THREAD

**Issue by egadstar** [rackt/redux-simple-router#128]
When using redux-simple-router in conjunction with the router's routerWillLeave lifecycle method, the routerWillLeave method is called twice. I'm assuming this is related to #109 or #108?

**Comment by kjbekkelund** [comment]
Hm, strange. Might be. I've got some busy days now before christmas so I don't have much time to check. If you want to test if #109 fixes your problem maybe you could test my branch in your app? That would be valuable input in ensuring we get this stuff right.

If so, you can add this to your `package.json`:

```
"redux-simple-router": "kjbekkelund/redux-simple-router#fix-double-update"
```

After `npm install` you have to `cd node_modules/redux-simple-router` and do a new `npm install`. This will build the lib, so you can use it in your app.

I'll also try to get this stuff tested more as soon as I've got some hours available.

**Comment by egadstar** [comment]
No problem, I'll give it ago. Thanks.

**Comment by egadstar** [comment]
Getting an error - "Uncaught SyntaxError: Unexpected token {" on this line -

function pushPath(path, state, { avoidRouterUpdate = false } = {}) {

I'll have to look into more later.

**Comment by kjbekkelund** [comment]
No problem, @egadstar — I'll try to get this tested as soon as I've got a bit of time

**Comment by jlongster** [comment]
@egadstar You probably didn't compile it, I think we have a problem when installing a custom branch where it doesn't compile the source. You can try to compile it by going into the folder and running `npm build`.

**Comment by kjbekkelund** [comment]
Haha, oups, forgot to include the build step above :/ Sorry, @egadstar. I need to write this down so I can copy/paste

**Comment by egadstar** [comment]
I had to change the build script to `mkdir -p lib && babel ./src/index.js --presets=es2015 --out-file ./lib/index.js` to get it to compile correctly, but I got it to build and the branch looks to have resolved the issue. Thanks.

**Comment by kjbekkelund** [comment]
Thanks for checking that out, @egadstar. Will try to get a fix released soon :)
