### ISSUE TITLE
When active it calls unregistered store listeners

### ISSUE THREAD

**Issue by kilianc** [rackt/redux-simple-router#130]
I am not sure how this happens but even if I 

```js
  componentWillUnmount () {
    console.log('%s: componentWillUnmount', this.constructor.name)
    this.unsubscribe()
  }
```

with `syncReduxAndRouter` active it will call the old listener and trigger a new setState with the warning and all

![](https://www.dropbox.com/s/7ti3davqi1d5tk7/Screenshot%202015-12-19%2008.11.50.png?dl=1)

**Comment by kjbekkelund** [comment]
Hi @kilianc. Not sure I understand what's going on here (not enough code to understand the context). Do you have a reproducible example I can take a look at?

**Comment by kilianc** [comment]
@kjbekkelund I just added you to my test app, to reproduce un comment lines in `app/bootstrap.jsx`

**Comment by kjbekkelund** [comment]
@kilianc Took a look at the app, not sure what's happening. We already [have a test](https://github.com/rackt/redux-simple-router/blob/master/test/createTests.js#L462-L492) that should cover unsubscribing, but might be there's something strange going on. I don't have the time right now to run your app and debug.

Btw, I'm not sure I see the need for your `BaseComponent`. When you [`connect`](http://rackt.org/redux/docs/basics/UsageWithReact.html#connecting-to-redux) your apps, you will already have access to the state. Use that to `mapStateToProps`, so you get access to the stuff you want from the store.

If you want to debug it more, it would be great if you find out the flow of stuff happening, so we could track when which actions are dispatched, received in `store.subscribe` and so on.

**Comment by kjbekkelund** [comment]
Also, as you can [see from the code](https://github.com/rackt/redux-simple-router/blob/master/src/index.js#L140-L143), we call directly to the underlying libs' `unsubscribe`, so hopefully we don't do anything in the lib that breaks unsubscribing

**Comment by kilianc** [comment]
@kjbekkelund I will get rid of BaseComponent and create a failing test case if I can so that we can nail it down if it's the lib's fault. I know I could have used `connect` but nothing stops me from subscribing manually everywhere, even if it's overhead... in theory.

I'll keep you posted.

**Comment by kjbekkelund** [comment]
@kilianc Great! :100:

**Comment by kilianc** [comment]
Getting rid of `BaseComponent` does it. I am still confused since didn't look like I was doing something wrong. Do you want me to create a bare minimum use case with a direct subscribe or just close this?

**Comment by kjbekkelund** [comment]
@kilianc That's good, at least. Not sure what happened here as I haven't got time right now to debug, but what would be awesome is having a test that covered this. If you've got time to try to create one, that would be great, but otherwise I think we'll close this for now and wait to see if someone else is bit by the same problem.
