### ISSUE TITLE
published package tarball includes node_modules/history

### ISSUE THREAD

**Issue by koba04** [rackt/redux-simple-router#133]
Currently, `redux-simple-router-1.0.1.tgz` includes `node_modules/history`.

```
➜  tree -L 2 package                                                                                                                                                                                                      [/Users/kobayashi/Desktop/test]
package
├── CHANGELOG.md
├── LICENSE
├── README.md
├── examples
│   └── basic
├── karma.conf.js
├── lib
│   └── index.js
├── node_modules
│   └── history
├── package.json
├── src
│   └── index.js
├── test
│   ├── browser
│   ├── createTests.js
│   └── node
└── tests.webpack.js
```

Because of this, `npm shrinkwrap` fails.

Related issues to this are here.

* https://github.com/npm/fstream-npm/pull/15
* https://github.com/npm/npm/issues/9642

Can you republish this with `npm@>2.14.10 || >3.4.0`?

**Comment by kjbekkelund** [comment]
Should be fixed by #134.

@jlongster Should we do a new release? We _could_ do a 1.0.2 directly off the 1.0.1 tag so we don't include the breaking(?) change related to init path on master.

**Comment by jlongster** [comment]
Hm, usually I like versions to be direct ancestors, but it is kind of annoying that we're still changing APIs and not able to push minor fixes. I guess there's nothing really wrong with cherry-picking changes for a minor release.

**Comment by jlongster** [comment]
Ok I just cherry-picked that change and published 1.0.2. Does that fix this issue?

**Comment by koba04** [comment]
@jlongster 

> I just cherry-picked that change and published 1.0.2

Thank you!
Released 1.0.2 package tarball still includes `node_modules/history`.

* https://registry.npmjs.org/redux-simple-router/-/redux-simple-router-1.0.2.tgz

What npm version did you use it? Does it match `>=2.4.10` or `>3.4.0`?

There are two ways for avoiding this issue


* Use the npm versions which is fixed the issue(`>=2.4.10 || >3.4.0`)
* Remove `node_modules/history` before publishing the package

You can test for this using `npm pack` command.

This is the npm scoped package which is fixed the issue.

* https://registry.npmjs.org/@koba04/redux-simple-router/-/redux-simple-router-1.0.2.tgz

**Comment by zhiyelee** [comment]
Any progress?

**Comment by jlongster** [comment]
Sorry, not yet. My npm version is 2.14.7. What changed in the later versions to fix this?

I can upgrade before releasing 2.0.0.

**Comment by zhiyelee** [comment]
@jlongster  https://github.com/npm/fstream-npm/pull/15  `history` is to general, haha

**Comment by zhiyelee** [comment]
https://github.com/npm/fstream-npm/pull/15#issuecomment-153935593

**Comment by koba04** [comment]
Soryy, my comment has mistake 😖

https://github.com/rackt/redux-simple-router/issues/133#issuecomment-167023468

> Use the npm versions which is fixed the issue(>=2.4.10 || >3.4.0)

correct: `>=2.4.10 || >3.4.0`

You should use npm version `>=2.4.10 || >3.4.0` for publishing the package.

**Comment by timdorr** [comment]
@jlongster Can you bump your version of NPM (`npm install -g npm`) and push again? I would do it myself, but I don't have publishing access :smile:

**Comment by jlongster** [comment]
Whoops, I meant to do that before I published. About to head to bed but I'll do it first thing in the morning.

**Comment by jlongster** [comment]
Should be fixed. Just published 2.0.3 with npm 3.5.3.

**Comment by timdorr** [comment]
Nope :( https://registry.npmjs.org/redux-simple-router/-/redux-simple-router-2.0.3.tgz

We had this issue on react-router, but I forget how it was resolved. Paging @taion!

**Comment by jlongster** [comment]
weird!

**Comment by taion** [comment]
It's resolved if you use npm2 :p

The bug wasn't properly fixed for npm3.

Otherwise, you can use something like https://github.com/rackt/react-router/blob/6bddfccd4d52dd0ab33298e91b13ed21f68e1135/scripts/release.sh#L52-L57.

**Comment by texttechne** [comment]
`redux-router` had the same problem. It's mentioned here with npm 3.5.2: https://github.com/acdlite/redux-router/issues/218#issuecomment-168631147

**Comment by taion** [comment]
@jlongster This was not fixed in 2.0.3. Until https://github.com/npm/npm/pull/10445 is merged, this will be broken in every version of npm3. You need to either use a recent npm2 or use the workaround of deleting `node_modules/history` (recursively if needed... ick) before publishing.

**Comment by koba04** [comment]
Sorry, I gave you incorrect information.
I thought it is fixed in the npm 3.4.0, but it is not...

**Comment by jlongster** [comment]
Yeesh, sorry it took so long to get around to this :/ This was a holiday weekend. I'm adding @timdorr, who's done an awesome job cleaning up issues, as a publisher on npm so I'm not the bottleneck there.

**Comment by zhiyelee** [comment]
thanks @jlongster

**Comment by timdorr** [comment]
Just pushed 2.0.4 with the fixed package. `node_modules` is gone :smile:  https://registry.npmjs.org/redux-simple-router/-/redux-simple-router-2.0.4.tgz

**Comment by zhiyelee** [comment]
COOL, thanks! @timdorr

**Comment by koba04** [comment]
Thanks! :tada:
