### ISSUE TITLE
dynamic routing and code splitting 

### ISSUE THREAD

**Issue by shangsunset** [rackt/redux-simple-router#135]
Hi,

Can i use redux-simple-router to migrate to redux from an app like react-router huge apps example? If so, where should i start? Thanks.

**Comment by kjbekkelund** [comment]
Hi @shangsunset, redux-simple-router only syncs the URL in the browser with a redux store, so hopefully it should be easy, but I haven't tested. Sadly I don't have time to help you get started on this right now. If you end up trying to do this, it would be great to hear about how it goes.

I'll keep this open a few days in case someone else has input. I also suggest creating a StackOverflow question — it might be easier to get answers there.

**Comment by taion** [comment]
The functionality in this repo doesn't touch on the code splitting at all. It should "just work".
