### ISSUE TITLE
gh-pages URL gets set to path property on Redux store

### ISSUE THREAD

**Issue by natac13** [rackt/redux-simple-router#139]
So I am **not** 100% sure this is where the issue lies but given the hack I used to fix my problem, I think it has something to do with redux-simple-router.

## Brief

I am build an app to store recipes. To start I am using redux to deal with state; that being a recipeList Immutable Map of recipe Maps. I am using react-router and therefore found this amazing project. I have it working great while in development. The setup was really easy thanks to the docs.

However when I push everything to gh-pages via the gh-pages module, and visit the site I get an error in the console about 'Location /vegan-recipe-app-redux/ does not match any routes. 

I added these lines 32-35 to my index.js file which is the entry to the app itself for webpack. 
![gh-pages-hack](https://cloud.githubusercontent.com/assets/10660283/12006599/c16a9f74-abaa-11e5-9712-23e549d67e49.png)

Now when visiting the site I see that the first `getState()` shows the path as /vegan-recipe-app-redux/
then changes to / to match the routes. I know this is a poor work around and was really hoping to get some help understanding what my real issue is and how to fix it. Or maybe it is something to do with redux-simple-router syncing with history???

![gh-pages-paths](https://cloud.githubusercontent.com/assets/10660283/12006610/31bf9978-abab-11e5-8e45-c824635c19d5.png)

**Comment by timdorr** [comment]
Is this fixed in 2.0?

**Comment by natac13** [comment]
So your saying I just need to update to 2.0 and I will not have to have the work-around code?

**Comment by timdorr** [comment]
I have no idea, but a lot of these older issues are obsoleted by 2.0, which was a pretty major refactor. I would try it out and see if the result is the same. If so, I'll open this back up and we can get to the bottom of things.

**Comment by natac13** [comment]
Sweet I will try it out!

**Comment by natac13** [comment]
@timdorr this was not fixed in 2.0
I am still using the hack to push a `'/'` path when the app loads. However I am then unable to refresh any page since the URL is not pointing the the right sub url of gh-pages. If I can provide anymore info please let me know.
