### ISSUE TITLE
#history redirect does not work with pushstate

### ISSUE THREAD

**Issue by JensDebergh** [rackt/redux-simple-router#145]
I'm creating a little login/registration form. 

When using `pushPath` action creator it does in fact update the URL but react-router does not respond to  the url change.

Any idea how or why this happens?

https://github.com/JensDebergh/toggle-client/blob/j-toker-login/app/action-creators/user.js

I'm using hashtag history API.

Thanks

**Comment by kjbekkelund** [comment]
You don't pass `history` to your `<Router>` in https://github.com/JensDebergh/toggle-client/blob/j-toker-login/app/routes.js. See https://github.com/rackt/react-router/blob/latest/docs/guides/basics/Histories.md

**Comment by JensDebergh** [comment]
Thanks for the quick answer !
My mistake :+1:
