### ISSUE TITLE
Initialize path with basename

### ISSUE THREAD

**Issue by neverfox** [rackt/redux-simple-router#146]
When using `useBasename`, the path in the address bar (and state) should be initialized with the basename path when the app inits. This is the behavior you got with redux-router and is also the behavior you get from Ember's router (when using their router's `rootURL`). This makes the association between history and state consistent from the very beginning. As it is now, the basename is only introduced into the browser history and state when the path is changed, e.g. with `pushPath`. (I'm using history 1.17.0 and redux-simple-router 1.0.2.

**Comment by neverfox** [comment]
Unfortunately, because of [this](https://github.com/rackt/history/blob/master/modules/useBasename.js#L30), and the fact that the configured basename isn't available to redux-simple-router (because it's just closed over), this would require a change to rackt/history.

**Comment by taion** [comment]
This is not the correct behavior from the POV of history/router, per https://github.com/rackt/history/pull/197. If the URL doesn't have the basename for some reason, it's not correct for the history to lie to you about what the basename of the current location is. You'll have to handle this redirect in userspace.
