### ISSUE TITLE
Authenticated route(s) with JWT method

### ISSUE THREAD

**Issue by es6Test** [rackt/redux-simple-router#150]
Hi, I was wondering if someone could provide an example of the best way to hook with up this router with login/authenticated state.

Ideally I would like to specified if any specified route(or any child routes) require authentication, and then redirection if not to login route.

thanks

**Comment by neverfox** [comment]
This library lets react-router do its thing, so the approach would be whatever approach works with react-router. There are examples of this out there:

https://github.com/auth0/react-flux-jwt-authentication-sample
https://github.com/lynndylanhurley/redux-auth
https://gist.github.com/iNikNik/1eabfc6bcc132384368c

**Comment by jlongster** [comment]
Yes, please ask this question in the react-router discord channel or some other place like that.
