### ISSUE TITLE
Documentation change: `pushState` doesn't trigger `hashchange` events

### ISSUE THREAD

**Issue by juanpaco** [rackt/redux-simple-router#152]
This may be common knowledge that I just discovered this morning, but TIL that the History API methods don't trigger `hashchange` events.  So if one is, for example and, uh, hypothetically speaking of course, using the hash history in `react-router` (yes, it's not the preferred method, but, well, reasons), then emitting `pushPath` events that change only the hash don't end up triggering `react-router` or anything else that relies on listening for `hashchange` events.

I don't think this is a bug with this project, but thought it might be worth mentioning in the documentation.  I'm happy to write that, if y'all also think it would be worthwhile.

**Comment by kjbekkelund** [comment]
Hi @juanpaco. As you don't have any code here it's difficult to see what the problem is, but redux-simple-router definitely works with hash history. Is this the same issue as https://github.com/rackt/redux-simple-router/issues/145? (i.e. you need to pass the same history to redux-simple-router as you do to react-router)

**Comment by juanpaco** [comment]
Derp.  Same problem indeed, *and* the example on the homepage does demonstrate using the same history object.  

Thank you for the help.

Are you interested in some doc language making it more explicit that the same object needs to be used?

**Comment by kjbekkelund** [comment]
There are some big changes going into master right now so we need to rework the docs and examples soon either way, so I think we can wait with doc changes.

**Comment by juanpaco** [comment]
Cool, cool.  Well, thanks for the project and Happy New Year!
