### ISSUE TITLE
Allow for npm install from GitHub

### ISSUE THREAD

**Issue by neverfox** [rackt/redux-simple-router#156]
I know this can be a contentious topic, but as the project is configured now, it's not possible to depend on the GitHub version of the library (for one, there's no build on install and, two, the `files` directive in package.json wouldn't provide the necessary files for one). At times like these, where major bug fixes are only available there until a new NPM release is published, this requires a fork with a committed build (as far as I know). I can live with that, but has anyone considered any acceptable reorganization of the project that makes a direct GitHub install possible?

**Comment by kjbekkelund** [comment]
I don't know what bugfix you're thinking of, but if you need to depend on `master`, you can add the master branch as a dep in `package.json`, then after `npm install` you need to `cd node_modules/redux-simple-router` and `npm install && npm run build`. But beware that master is _very_ different from `1.0.2`.

**Comment by neverfox** [comment]
That's just it though. You cannot do that because of the `files` section of package.json. When you install from master, the only things that will end up in your `node_modules` are  the two *.md files, LICENSE, and package.json; none of the source code. So the naive suggestion is to remove the `files` section from package.json so that I can do a post-install build. I imagine though that that will have some impact on your publication process because you don't want those files to go to npm. In that case, you could use an .npmignore file

> But beware that master is very different from 1.0.2.

Yes, indeed, and I've already got my code refactored to work with the changes. It was a necessity because the double updates were killing my navigation.

**Comment by neverfox** [comment]
I'm happy to do a PR if that sounds like an acceptable solution.

**Comment by kjbekkelund** [comment]
Ah, so that's actually a con of https://github.com/rackt/redux-simple-router/pull/134 — didn't think about this use-case. I'll re-open and wait and see if others have any opinions on this. Hopefully we'll get a 2.0 out soon too.

**Comment by koba04** [comment]
Indeed, how about adding `src` to the `files`?
I think it can cover this use case.

https://github.com/koba04/redux-simple-router/commit/90ac7ce771cf6bfdc5e55b4673772fabaa1575bf

```
% npm install https://github.com/koba04/redux-simple-router.git#add-src-to-files-fields
% cd node_modules/redux-simple-router
% npm install && npm run build
:
:
% tree -L 1
.
├── CHANGELOG.md
├── LICENSE
├── README.md
├── lib
├── node_modules
├── package.json
└── src
```

**Comment by neverfox** [comment]
I guess the obvious question is "Why limit it in the first place?"

**Comment by koba04** [comment]
I think `npm install` should only include files that are required to use it.
I think  an opt-in approach with `files` fields is better than an opt-out approach with `.npmignore`, because managed files by a project can be increasing over time.

I guess `npm install ${github.repo}` is not the common use case.
In many other libraries, `npm install ${github.repo}` have different results from npm install ${library}` and its GitHub repository.

Additionally, in many cases, `npm install ${github.repo}` requires some custom scripts to use it.
In this case, I guess it should be used the forked repository that is added scripts for a build.

As a result, I think it is enough to add `src` to `files` fields.

https://github.com/koba04/redux-simple-router/commit/90ac7ce771cf6bfdc5e55b4673772fabaa1575bf

**Comment by neverfox** [comment]
> I think npm install should only include files that are required to use it.

From the registry sure, but when you are specifically requesting the master branch from GitHub, I think you should get...the master branch from GitHub. At that point, you are using NPM as a transport mechanism for something else.

And what about the tarball? Don't you think it should be an archive of the repo as it existed at a certain release, not just what you publish to NPM, which is really an unrelated concern?

**Comment by koba04** [comment]
Indeed, I think the npm registry is not an archive site. It is a registry for npm as a package manager.
If I need an archive of the repository, I am usually using `git clone` from GitHub(master or releases).

**Comment by jlongster** [comment]
I think @koba04 is right. For now let's just add `src` to the `files` field. Installing from `npm` and then manually running `npm install` inside the module works now.

I wish npm just ignored these fields when installing straight from a git repo. I would expect to get the full repo, but this works for now.
