### ISSUE TITLE
pushPath and replacePath have now changed to transition but I cannot find documentation on how to use them

### ISSUE THREAD

**Issue by StevenIseki** [rackt/redux-simple-router#158]
The following commit https://github.com/rackt/redux-simple-router/commit/243235eb7c1c9c5c79ab22e2e1eddc88123357d2#diff-1fdf421c05c1140f6d71444ea2b27638 changed pushPath() and replacePath() to now export push and replace as const's. Can the new way it works be documented in the README, as it currently still shows how to use replacePath and pushPath, and I am not sure how to implement this now. 

I was previously following the basic example:

```jsx
<button onClick={() => pushPath('/foo')}>Go to /foo</button>
```

Thanks

**Comment by kjbekkelund** [comment]
It still isn't released. It will be documented when we release 2.0 — hopefully quite soon. The current readme works for 1.0.2
