### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined using pushPath()

### ISSUE THREAD

**Issue by StevenIseki** [rackt/redux-simple-router#159]
I get the following error when running the basic example and trying to use `pushPath()` for instance on a button click:

```jsx
<button onClick={() => pushPath('/foo')}>Go to /foo</button>
```

**Uncaught TypeError: Cannot read property 'apply' of undefined**

Error is using the [1.0.2 basic example](https://github.com/rackt/redux-simple-router/tree/1.0.2/examples/basic)

**Comment by jcsmesquita** [comment]
+1

**Comment by annelorraineuy** [comment]
+1

**Comment by jlongster** [comment]
How did you get the app running? By default it pulls from master, where the API has changed. I'm going to release 2.0.0 today or tomorrow so they will be in sync.
