### ISSUE TITLE
simplified example

### ISSUE THREAD

**Issue by jasonswearingen** [rackt/redux-simple-router#161]
As my own self-directed learning I redid the basic example as a single file instead of spread among lots of files/folders, and added a lot of documentation.

I wrote it in typescript, the .TSX can be found here:   https://gist.github.com/jasonswearingen/44068ebe04b1b077c8c9

Maybe consider using this as a replacement for the current example?  If no, no hard feelings! :+1: 

PS: sorry it's in typescript (not ES6)   it's almost the same, just need to remove the "typings" (things like  ```:number``` in ```var x:number = 5;```

**Comment by StevenIseki** [comment]
I think the current basic example is extremely simple and an excellent starter guide for using redux simple router. Except for the slight conflict between it using version 2.0 at the moment, which means you have to use the https://github.com/rackt/redux-simple-router/tree/1.0.2/examples/basic tag version, which I think I will create a pull request to give new users a hint on. 

Your example looks nice, I do not use TypeScript myself, I use Babel and es6 which I think a lot of react developers do, I would consider if you wanted to make your gist a simplified example repo, as minimal as you possibly can but still possible to build it and run easily with instructions. Then if you like create a pull request on the [README](https://github.com/rackt/redux-simple-router/blob/master/README.md) to add your example and the maintainers will have a look at it and possibly add it to the list of examples.

Nice work :+1:

**Comment by timdorr** [comment]
If you don't mind, submitting it as a PR would be best. However, given its written in a language none of us use, that would make it harder to accept. We could definitely link to a repo in the examples section!
