### ISSUE TITLE
What is the preferred way to get query parameters?

### ISSUE THREAD

**Issue by AsaAyers** [rackt/redux-simple-router#165]
Given the following link was clicked: `<Link to="/" query={{ id: 10, limit: 20 }}>Next</Link>` I end up with

```js
store.getState().routing.path === "/?id=10&limit=20"
```

Nothing in `routing` contains a usable version of the query, so are components expected to somehow obtain a reference to the `history` object passed into the `<Router/>`?

**Comment by ranadeep47** [comment]
https://github.com/rackt/redux-simple-router/blob/243235eb7c1c9c5c79ab22e2e1eddc88123357d2/test/createTests.js#L26

This helps ?

**Comment by mjrussell** [comment]
@AsaAyers I recommend using the 2.x version of of simple-router because it contains the entire location object including the query object. Its not fully stable/released yet but you can use the version by `npm install --save redux-simple-router@next`

**Comment by AsaAyers** [comment]
Thanks. I just went back to `redux-router`. I was starting a new project last night and saw the big warning on the home page to move to this, so I tried it. This issue tells me that this project just isn't ready for me to use yet.

**Comment by jlongster** [comment]
Most of the time you can just reference everything from react-router in the routing components: https://github.com/rackt/react-router/blob/latest/docs/API.md#route-components That is the biggest insight of this library. Many people didn't even realize that before. You should just use react-router directly, and pass things down to children when needed.

We realize that there are some edge cases where it's useful to store more information in the store, but if you are in routing components already you really should just use react-router directly.

**Comment by jlongster** [comment]
If you try `redux-simple-router@next` we do store the parsed location object into the store now, so you can access query params.

**Comment by AsaAyers** [comment]
Thanks. I didn't even think to use the props injected props. I was just trying to write my [`mapStateToProps` for connect](https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options) and the info I need isn't in the store.

One of the things I like about `redux-router` is that the store is the single source of truth. You may have simplified the code for this library, but it doesn't simplify using it in it's current version. I'll come back and try this when I think I have time to switch again or start a new project.

**Comment by jlongster** [comment]
It does simplify using it. Everything complicated like server-rendering has to be reinvented with redux-router, and *many* people came to this and found that using react-router directly was much simpler.

Totally fine if it doesn't work for you and you find redux-router to me more your taste though :)

**Comment by robertfall** [comment]
For what it's worth I ran into the same issue as @AsaAyers with regards to `mapStateToProps` and have dropped react-simple-router in favour of react-router because of it in the past. I was not in fact aware that react-router passed in the params as props on children, or had forgotten. But I was also not aware (or had forgotten) about the 2nd argument to mapStateToProps and struggled to find an example using react-redux, react-router-redux and a url parameter. 

Extending the examples to show the use of a query parameter would be very helpful and I'll submit a PR tomorrow. In the mean time, in case anyone stumbles onto this issue, one can get url parameters from the 2nd argument to mapStateToProps as follows:

```
function mapStateToProps(state, ownProps) {
   return {
      stateData: state.data,
      id: ownProps.params.id,
   };
}
```

https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

**Comment by mmahalwy** [comment]
I have been unsuccessful with getting query on the server. See:

```
app.use((req, res, next) => {
  if (__DEVELOPMENT__) {
    // Do not cache webpack stats: the script file would change since
    // hot module replacement is enabled in the development env
    webpackIsomorphicTools.refresh();
  }
  const client = new ApiClient(req);
  const history = createHistory();
  const store = createStore(getRoutes, history, client);

  function hydrateOnClient() {
    res.send('<!doctype html>\n' +
      ReactDOM.renderToString(<Html assets={webpackIsomorphicTools.assets()} store={store}/>));
  }

  if (__DISABLE_SSR__ || req.query.DISABLE_SSR) {
    hydrateOnClient();
    return;
  }

  match({ history, routes: getRoutes(store), location: req.originalUrl }, (error, redirectLocation, renderProps) => {
    function throwError(type, error) {
      console.error(`${type}: `, pretty.render(error));
      next(error);

      res.status(500);
      res.send(ReactDOM.renderToString(
        <Html assets={webpackIsomorphicTools.assets()} component={<Oops errorCode={res.sentry}/>} store={store}/>
      ));
    }

    if (redirectLocation) {
      res.redirect(redirectLocation.pathname + redirectLocation.search);
    } else if (error) {
      throwError('ROUTER ERROR:', error);
    } else if (renderProps) {
      loadOnServer(renderProps, store, {client}).then(() => {
        const component = (
          <Provider store={store} key="provider">
            <ReduxAsyncConnect {...renderProps} />
          </Provider>
        );

        res.status(200);
        // global.navigator = {userAgent: req.headers['user-agent']};
        res.send('<!doctype html>\n' +
          ReactDOM.renderToString(<Html assets={webpackIsomorphicTools.assets()} component={component} store={store}/>));
      }).catch(error => {
        throwError('ROUTES ERROR:', error);
      });
    } else {
      res.status(404).send('Not found');
    }
  });
});
```

**Comment by timdorr** [comment]
Is that with React Router 2.0?

**Comment by mmahalwy** [comment]
yes
