### ISSUE TITLE
Worth updating the examples?

### ISSUE THREAD

**Issue by ericdfields** [rackt/redux-simple-router#170]
At least the basic example is out of date, pretty much in conflict with the README, which is confusing.

I'd be happy to update if we think the examples are going to stick around. A lot of activity on this project, so I don't want to update something that won't be around in a month or so :)

**Comment by annelorraineuy** [comment]
+1

**Comment by StevenIseki** [comment]
There are a few good examples in the README, I have a basic example using the current published version 1.0.2 [redux-simple-router-example](https://github.com/StevenIseki/redux-simple-router-example) however it has isomorphic-fetch and css modules support too so is not quite as minimal.
[tj/frontend-boilerplate](https://github.com/tj/frontend-boilerplate) is another good boilerplate example using redux-simple-router.

I think if you create a basic example, and add a pull request to the README it would be quite helpful.

Some of the problems getting started with the basic example were discussed in this [pull request](https://github.com/rackt/redux-simple-router/pull/154), I think the consensus was that the current basic example is for development and uses the latest version of redux-simple-router so you need to `npm install` the root project, unless you clone the `1.0.2 tag` and make the suggested modification to the `webpack.config`.
