### ISSUE TITLE
Using react-router's <Link/> component causes double history entries

### ISSUE THREAD

**Issue by kromit** [rackt/redux-simple-router#171]
`history.push(location)` is called two multiple times with the same values:

* first time when the `<Link>` is clicked
* second time when route store listener is called:

        var unsubscribeStore = store.subscribe(function () {
             var routing = getRouterState();
             // Only trigger history update if this is a new change or the
             // location has changed.
             if (lastRoute.changeId !== routing.changeId || !locationsAreEqual(lastRoute, routing)) {

                 lastRoute = routing;  
                 var method = routing.replace ? 'replaceState' : 'pushState';
                 history[method](routing.state, routing.path);
             }
         }

This always calls `history.pushState` for second time because history/router and browser window already have the new location but `lastRoute` still contain old `path`. This effectively causes two equal history entries so the browser back button works on the second click only. 

The current history location and window.location should be checked before `history.push` to prevent duplicate history entries.

**Comment by ernoaapa** [comment]
I have this same issue.

**Comment by BerkeleyTrue** [comment]
@kromit Have you tried it with the new version https://github.com/rackt/redux-simple-router/blob/master/src/index.js#L99

It shouldn't have the same problem since it uses the key created by RR.

**Comment by kromit** [comment]
2.0.1 fixed it
