### ISSUE TITLE
update peerDependency to react 0.14.x

### ISSUE THREAD

**Issue by Beingbook** [rackt/redux-simple-router#174]
Hi. I'm using redux-simple-router v2 with react. the peerDependency makes `UNMET PEER DEPENDENCY react@0.14.5` in every installation. It's perfectly easy to update. Will you do?

Thank you!

**Comment by mjrussell** [comment]
@Beingbook there aren't any peerDependencies in v2 : https://github.com/rackt/redux-simple-router/blob/master/package.json. I think you might have another NPM dependency issue.

NPM log?

**Comment by Beingbook** [comment]
@mjrussell you rights, it's react-simple-router@0.1.6 error. but I pointed the tag of next.... I don't know why this happened.

**Comment by Beingbook** [comment]
Oh my god... It's perfectly my fault. It was `react-simple-router` not `redux-simple-router` sorry...
