### ISSUE TITLE
Can route.name be included in the router state?

### ISSUE THREAD

**Issue by AlistairB** [rackt/redux-simple-router#175]
Hi,

Can route.name be included in the router state?

I want to have this feed into my App -> NavBar -> h1. Whilst I can access this.props.route.name in my components as it isn't in the redux router state changes to it don't update the NavBar.

Or can I achieve this some other way?

Cheers

**Comment by calebthebrewer** [comment]
I'm in a similar situation as @AlistairB except I want to access route parameters.
#### Use case
My `mapStateToProps` method which connects a dumb component to my state is conditional on the route. That is to say, on the route `/data/:id`, the data with the matching `id` should be mapped to a different property than the rest of the data, (where I have an array of `data` in my state).

Currently I can access the `id` via `props.params.id` from the dumb component, it would be cool if I could also access the parameters in my map function so the component itself doesn't have to be aware of this convention.

**Comment by mjrussell** [comment]
@calebthebrewer use the second argument of the mapStateToProps function. Its passed in via being a rendered component of React-Router. Note this only works for components directly rendered by a Route (or you'd need to use the context in RRv2 or a mixin in RRv1) https://github.com/rackt/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options

```js
function mapStateToProps(state, ownProps) {
   return {
      stateData: state.data,
      id: ownProps.params.id,
   };
}

**Comment by calebthebrewer** [comment]
Thanks @mjrussell, I missed that in the docs. It looks like `ownProps.route.name` is also available - does this resolve your issue @AlistairB?

**Comment by AlistairB** [comment]
No unfortunately this doesn't solve my issue.

I want to have something like this:

```
const mapStateToProps = (state, ownProps) => ({
  pageTitle: ownProps.route.name
})
class CoreLayout extends React.Component {

  static propTypes = {
    pageTitle: React.PropTypes.string.isRequired,
    children: React.PropTypes.element.isRequired
  };

  render () {
    const { children, pageTitle } = this.props

    return (
      <div className='page-container'>
        <div className='view-container'>
          <NavBar pageTitle={pageTitle} />
          {children}
        </div>
      </div>
    )
  }
}

export default connect(mapStateToProps)(CoreLayout)
```

Which doesn't work. It initially will render whatever is in   ```<Route name='test' path='/' component={CoreLayout}>``` then it get's cleared. I think because this is a global component AND because these additional parameters are not in the global state I can't have them update on route change.

The work arounds I can think of are:

1. I could use UPDATE_PATH to listen to route changes and populate a pageTitle in the state somewhere.
2. I could include NavBar in my top level page components which will get updated when the route changes.

1 seems the best. Is there are better way?

**Comment by mjrussell** [comment]
@AlistairB I think you have other issues in your project...passing down the page title from the CoreLayout down to NavBar will in fact update the nav bar correctly when pageTitle is updated. 

That just how react works (on its own without redux). If any props that are passed to a component are updated, the render() function is always called unless you have a shouldComponentUpdate check. 

React-Router will pass these updated props down on every route change with or without `redux-simple-router`. Might need a full gist/github repo to actually diagnose the real problem. I'd advise using the react-devtools (https://github.com/facebook/react-devtools) and inspecting the props passed down to your components

**Comment by AlistairB** [comment]
Ok thanks. I'll do some more investigation and close this for now.
