### ISSUE TITLE
When Compose with (thunk_middleware,redux_simple_middleware,promise_middleware) couldn't get dispatch function return value

### ISSUE THREAD

**Issue by vimalceg** [rackt/redux-simple-router#176]
![screen shot 2016-01-08 at 4 58 58 pm](https://cloud.githubusercontent.com/assets/14313723/12197131/7383ee52-b62a-11e5-91a7-995b9940a410.png)

example
     dispatch(ajaxPromiseCall).then(function(res){
             console.log(res)
})
I couldn't get promise while dispatch call . because of the middleware not returning. 
"return next(action)"

**Comment by Furizaa** [comment]
Fixed in https://github.com/rackt/redux-simple-router/pull/178
