### ISSUE TITLE
Getting `You cannot change <Router routes>; it will be ignored` when hot-loading

### ISSUE THREAD

**Issue by Saturn2888** [rackt/redux-simple-router#179]
When hot-loading I am getting the warning:

```warning
You cannot change <Router routes>; it will be ignored
```

My process is I save a file in view with some update like I added a `<span>`, and it shows up on the page, but then this error shows. I checked into it, finding the commit here: https://github.com/rackt/react-router/commit/62f6ef24136b2b80472931e785a75c358e993e90

I don't know what this does. It looks like it's saying if you're on the current page and the route doesn't change, but everything else stayed the same, then warn.

**Comment by ppalladino** [comment]
+1 Same issue.

**Comment by jlongster** [comment]
This sounds like a react-router issue. Please file there; re-open this if I'm wrong.

**Comment by tomasz-szymanek** [comment]
+1 same here. reproduced by doing this:

`const renderAll = () => {
  ReactDOM.render(
    (
      <Provider store={store}>
        <Router history={browserHistory}>
          <Route path="/" component={App}>
            <Route path="about" component={About} />
            <Route path="posts" component={Posts}>
              <Route path="/post/:nr" component={Post} />
            </Route>
            <Route path="*" component={NoMatch} />
          </Route>
        </Router>
      </Provider>
    ), document.getElementById('root')
  );
};

store.subscribe(renderAll);
renderAll();`

**Comment by amertak** [comment]
Started to get the same error.

**Comment by haim-rubin** [comment]
Hi,
Is someone of you found solution for this error?
Thanks!

**Comment by amertak** [comment]
I found solution for my problem.
I am using shared component for all other components as a parent (it has services and other things in constructor). The problem was, that also containers used this shared component and change of every component in app went directly to router through container. 
My "solution" was not to use this shared component for Containers (components defined in router routes). Hope this helps

**Comment by lauterry** [comment]
hi @amertak

I have the same issue. 

I can't see what you're talking about.

Can you explain with some code snippet please ?

Best regards

**Comment by amertak** [comment]
I try.

`<Provider store={store}>
	<Router history={history}>
		<Route path="/sessions" component={Sessions} />
		<Route path="/recordings" component={Recordings} />
		<IndexRoute component={VisitorList}/>
	</Router>
</Provider>`

My problem was, that all the containers (`Sesions`, `Recordings`, `VisitorList`) had been using as a parent not `Component` from React, but my component called `DashboardComponent `

`export default class DashboardComponent extends Component { ...`

Also all other components in app were using `DashboardComponent` so if I changed something it went up to the container -> changed the router -> threw error

**Comment by OriolBonjoch** [comment]
Hi all,

Same happened here and the solution was declaring the routes object outside of the render method as PlainRoutes, so it doesn't get updated. So taking @tomasz-szymanek code it would be something like:

```javascript
const routes = {
    path: '/',
    component: App,
	childRoutes: [
        { path: '/about', component: About },
        {
			path: '/posts',
			component: Posts,
			childRoutes: [ { path: '/post/:nr', component: Post } ]
		},
		{ path: '*', component: NoMatch}
	]
};

const renderAll = () => {
  ReactDOM.render(
    (
      <Provider store={store}>
        <Router history={browserHistory} routes={routes} />
      </Provider>
    ), document.getElementById('root')
  );
};

store.subscribe(renderAll);
renderAll();
```

That way the routes list is not changed and works in a redux way.

**Comment by boneyao** [comment]
thanks @OriolBonjoch  it works for me!

**Comment by tomasz-szymanek** [comment]
You are god to me @OriolBonjoch

**Comment by Kitanotori** [comment]
The PlainRoutes suggested by @OriolBonjoch didn't work for me. Is there an actual working example of react-router-redux with hot reloading?

**Comment by OriolBonjoch** [comment]
react-router complains if the history is changed in a Router component (which if you have one Router component for each url route makes sense, if you change url you unmount this one and mount another one).
And then react-router-redux sets a history in the redux store so a change in the url is propagated to the store. Since redux propagates the history in the top level Provider component the history is propagated to lower components and changed twice by the react-router Router component state (first by react-router and then by Provider store).

So my guess is that react-router-redux patches the use of react-router in redux, hence the warning is completly expected in development which matters nothing (except for being really annoying). As solution I don't know, create a new redux based router not based on react-router?

**Comment by OriolBonjoch** [comment]
First of all that is a warning that doesn't stop anything, its just annoying.

I think this happens because of react-redux top level Provider component. It triggers the componentWillReceiveProps in Route component even when they haven't really changed (component and path remains the same but is a new object since you created it inside render function).

Besides that I'm curious, @Kitanotori in what case you modified the routes in runtime?

**Comment by Kitanotori** [comment]
@OriolBonjoch It stops the hot reloading. The changes I make to the route components are not being hot reloaded.

I will post an example app to Github soon in order to explain the issue better.

**Comment by Kitanotori** [comment]
@OriolBonjoch It seems that I somehow got it working in the example I built. I wonder what I did differently in my main project... Have to examine further.

Here is an example of how to set up React, Redux, Saga, and routing together with Webpack, Babel, and hot reloading: https://github.com/Kitanotori/react-webpack-babel-hotreload-example

**Comment by dceddia** [comment]
@Kitanotori I think the reason your approach worked is because you extracted the routes into a module, so they were only declared once, instead of recreating them with every render.

I wasn't using react-router-redux, but I did have some state in my Root component for growl-style notifications, and I was getting this "cannot change Router..." warning.

I was able to get the warning to go away by extracting my routes. Before:

```jsx
class Root extends Component {
  render() {
    return (
      <Router history={browserHistory} createElement={this.createElement}>
        <Route component={App}>
          <Route path="/" component={MainPage}/>
          <Route path="/page2" component={Page2}/>
          <Route path="/settings" component={SettingsPage}/>
        </Route>
      </Router>
    )
  }
}
```

After:

```jsx
const routes = (
  <Route component={App}>
    <Route path="/" component={MainPage}/>
    <Route path="/page2" component={Page2}/>
    <Route path="/settings" component={SettingsPage}/>
  </Route>
);

class Root extends Component {
  render() {
    return (
      <Router history={browserHistory} createElement={this.createElement}>
        {routes}
      </Router>
    )
  }
}
```

**Comment by deryost** [comment]
In my case the bug was the forceUpdate method called by subscribing to the redux store...

**Comment by jeznag** [comment]
In my case, the issue seems to occur when passing props to the routes. When the props change, the warning is fired.
```
<Router history={browserHistory}>
        <Route path='/' component={LoginComponent} />
        <Route path='/login' component={LoginComponent} />
        <Route path='/chooseCourse' component={ChooseCourseComponent} {...this.props} />
        <Route path='/doCourse/:courseID' component={DoCourseComponent} {...this.props} />
        <Route path='/doCourse/:courseID/:sectionID/:topicID' component={DoCourseComponent} {...this.props} />
      </Router>
```

I don't know how to get around this. Any ideas?

**Comment by hiddentao** [comment]
I had this problem too and it turned out it was due to the same thing as @amertak had. I had a base component which all my other components inherited, so every change caused HMR to propagate up to route definitions and then subsequently the root component. Bizarre.

**Comment by OriolBonjoch** [comment]
@jeznag those properties are for Route component (like history or children)? If its not like that I would add it in ChooseCourseComponent and DoCourseComponent connect props.

**Comment by jeznag** [comment]
@OriolBonjoch yeah good point. I ended up doing that :) Misunderstood redux and thought I could only have one connected component.

**Comment by hiddentao** [comment]
in case it helps anyone else, here is my code:

```js
// app.js
...
const store = createStore(),
  routes = createRoutes(store);
  
ReactDOM.render(
  <Provider store={store}>
    <Router history={hashHistory}>
      {routes}
    </Router>
  </Provider>,
  document.getElementById('react-root')
);

// routes.js
...
export function create(store) {
  ...
  return (
    <Route>
      <IndexRoute component={InitPage} />
      <Route path="/editor" component={EditorPage}/>
      <Route path="*" component={InitPage}/>
    </Route>    
  );
}
```

Ensure your components inherit directly from `React.Component` and not some intermediate base class. This was what caused problems for me. If I figure out how to make it work with an intermediate base class I'll let you know.

**Comment by DragonFire353** [comment]
I am unable to get this working with getComponent. I'm trying to code split my app by routes using System.import and Webpack 2. Although I am unable to get code splitting working using any method for some reason, hot reload does not work when using both getComponent and Provider:

App.js:

```
...
const store = configureStore();
const history = syncHistoryWithStore(browserHistory, store);

const mountNode = document.querySelector('#app');

render(
	<AppContainer>
		<Root store={store} history={history} />
	</AppContainer>, mountNode);

if (module.hot)
	module.hot.accept('./Root', () => {
		render(
			<AppContainer>
				<Root store={store} history={history} />
			</AppContainer>, mountNode);
	});
```

Root:

```
...
const Root = ({ store, history }) => {
	return (
		<Provider store={store}>
			<Router routes={routes} history={history} />
		</Provider>
	);
}
```

routes.js:

```
import MainLayout from 'containers/MainLayout/MainLayout';
import index from './views/Index/routes';
...

export default {
	component: MainLayout,
	childRoutes: [
		index,
		...
	]
}
```

index routes.js:

```
import Container from './Container';
import { loadRoute, errorLoading } from 'helpers/route';

export default {
	path: '/',
	getComponent: (location, cb) => System.import('./Container').then(loadRoute(cb)).catch(errorLoading)
};
```

Container.jsx:

```
export default class Container extends React.Component {
	render() {
		return (
			<div>
				Home
			</div>
		);
	}
}
```

**Comment by hiddentao** [comment]
@DragonFire353 Why do you repeat the render in the reload hook?

```js
if (module.hot)
    module.hot.accept('./Root', () => {
        render(
            <AppContainer>
                <Root store={store} history={history} />
            </AppContainer>, mountNode);
    });
```

**Comment by DragonFire353** [comment]
@hiddentao because that's what was in the example for hot loader 3: https://github.com/gaearon/redux-devtools/blob/64f58b7010a1b2a71ad16716eb37ac1031f93915/examples/todomvc/index.js

**Comment by DragonFire353** [comment]
hmmm it works if I make Root an actual React Component:

```
export default class Root extends React.Component {
  render() {
    const { store, history } = this.props;
		return (
			<Provider store={store}>
				<Router routes={routes} history={history} />
			</Provider>
		);
	}
}
```

Not sure why there'd be a difference with this when it was working without Provider. Still get the warning though. And code splitting doesn't work but that's a separate issue...

**Comment by markbame-github** [comment]
thanks!

**Comment by heldrida** [comment]
I'm getting the error Warning: [react-router] You cannot change <Router routes>; it will be ignored

index.js
```

import React from 'react';
import { render } from 'react-dom';
import { browserHistory } from 'react-router';
import { syncHistoryWithStore } from 'react-router-redux';
import { AppContainer } from 'react-hot-loader';
import Root from './root';
import configureStore from './store'

const store = configureStore({});
const history = syncHistoryWithStore(browserHistory, store);

render(
  <AppContainer>
  	<Root store={ store } history={ history } />
  </AppContainer>,
  document.getElementById('app')
);

if (module.hot) {
  module.hot.accept('./root', () => {
	const NextRoot = require('./root').default;
    render(
      <AppContainer>
      	<NextRoot store={ store } history={ history } />
      </AppContainer>,
      document.getElementById('app')
    );
  });
}
```

root.js
```

import React, { Component } from 'react';
import ReactDOM from "react-dom";
import { Router, browserHistory } from 'react-router';
import { routerMiddleware, push } from 'react-router-redux';
import routes from './routes';
import { Provider } from 'react-redux';
import configureStore from './store'

export default class Root extends Component {
  render() {
    return (
		<Provider store={ this.props.store }>
			<div>
				<Router history={ this.props.history } routes={ routes } />
			</div>
		</Provider>
    );
  }
}
```

routes.js
```

import React from 'react';
import { Route, IndexRoute } from 'react-router';
import App from './containers/app';

const routes = (
	<Route path='/' component={ App }>
	</Route>
);

export default routes;
```

webpack.dev.config
```

var path = require("path");
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
	historyApiFallback: true,
	entry: [
		'webpack-dev-server/client?http://localhost:3000',
		'webpack/hot/only-dev-server',
		'react-hot-loader/patch',
		'./src/js/index.js'
	],
	output: {
		path: __dirname + '/static',
		filename: "index_bundle.js",
		publicPath: '/'
	},
	module: {
		loaders: [
			{ test: /\.js$/, exclude: /node_modules/, loaders: ["babel-loader"] },
            { test: /\.scss$/, loader: 'style!css!sass' },
			{ test: /\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9=&.]+)?$/, loader: 'file-loader' }
		]
	},
	plugins: [
		new HtmlWebpackPlugin({
			inject: true,
			template: __dirname + '/src/' + 'index.html',
			filename: 'index.html'
		}),
		new webpack.DefinePlugin({
			'process.env': {
				'NODE_ENV': JSON.stringify('development')
			}
		}),
		new webpack.HotModuleReplacementPlugin(),
		new webpack.NoErrorsPlugin()
	]
};
```

app.js
```

import React, { Component } from 'react';

class App extends Component {
	render() {

		return (
			<div className="app">
				<h1>Reaclux Boilerplate 2</h1>
				<p>A React Redux Webpack Gulp Sass Mocha Enzyme Zombie Chai Boilerplate by <span>Punkbit</span></p>
			</div>
		);

	}

}

export default App;
```

**Comment by kevin-miles** [comment]
I also resolved this by doing the same as https://github.com/reactjs/react-router-redux/issues/179#issuecomment-251182228 

Moving root to an actual component worked.

**Comment by bochen2014** [comment]
@heldrida  same here.
@kevin-miles  yes it will work, but the warning won't go away.

I dug into the problem, and kind of believe that it can't be fixed ---- to be able to reload the module that was changed (let's say,, index.js), we need to ask the parent component, which is routes.js in this case,  to be re-rendered. However, `react-router` is not happy to re-render because router is not supposed to be re-rendered (we normal don't have dynamic router. it's always static router which is determined at design time). 
@gaearon may give a better answer

**Comment by bochen2014** [comment]
sorry. I think we are discussing in the wrong place. 
We are talking about `react-hot-loader` issues within `react-router-redux` repository

sorry about that, google brought me in after I put the warning message as key word

**Comment by swamikevala** [comment]
How do I get around this problem if I'm using onEnter, and the function uses props? 

```
requireAuth(nextState, push, callback) {
  let redirect = nextState.location.pathname
  if (this.props.isAuthenticated) {
    if ( pageAuthorized(redirect, this.props.roles) )  
      callback()
    else
      browserHistory.push('/unauthorized') 
  } else 
    this.props.pageAccessAttemptCallback(redirect)
}

render() {
  return (
    <Router history={browserHistory}>
      <Route path="/" component={NavigationBarContainer}  >
        <Route path="/search" component={SearchPageContainer} onEnter={this.requireAuth} />
        <Route path="/merge" component={MergePageContainer} onEnter={this.requireAuth} />
        <Route path="/edit" component={EditPageContainer} onEnter={this.requireAuth} >
          <Route path="/edit/:guid" component={EditPageContainer} onEnter={this.requireAuth} />
        </Route>
        <Route path="/clean" component={CleanPageContainer} onEnter={this.requireAuth} />
        <Route path="/unauthorized" component={UnauthorizedPage} />
      </Route>
      <Route path="/login" component={LoginPageContainer} />
    </Router>
  )
}
```

**Comment by jmahc** [comment]
@bochen2014 I'm beginning to think the same thing regarding react-router

**Comment by AvraamMavridis** [comment]
I have the same problem @swamikevala 

```
class App extends Component
{

  requireAuth(nextState, replace) {
    if (!this.props.user.isLoggedIn) {
      replace({
        pathname: '/',
        state: { nextPathname: nextState.location.pathname }
      })
    }
  }

  render()
  {
    return (
        <Router history={history}>
          <Route path="/" component={MainContainer}>
            <IndexRoute components={{ Home: Home }}/>
            <Route path="home" components={{ Home: Home }}/>
            <Route path="squad" components={{ Team: Team }} onEnter={this.requireAuth.bind(this)}/>
          </Route>
        </Router>
    );
  }
}
```

**Comment by jmahc** [comment]
What worked for me:

**Root.jsx**
```
import React, { Component, PropTypes } from 'react';
import { Provider } from 'react-redux';
import { Router } from 'react-router';
import routes from '../../routes';

export default class Root extends Component {
  static propTypes = {
    history: PropTypes.object.isRequired,
    store: PropTypes.object.isRequired,
  };

  render() {
    const { history, store } = this.props;
    return (
      <Provider store={store}>
        <Router history={history} routes={routes} />
      </Provider>
    );
  }
}
```

My entry file:
```
// ==== Node Modules
//
import React from 'react';
import ReactDOM from 'react-dom';
import { AppContainer } from 'react-hot-loader';
import { syncHistoryWithStore } from 'react-router-redux';
import { hashHistory } from 'react-router';
import { createStore } from 'redux';
import injectTapEventPlugin from 'react-tap-event-plugin';

// ==== Local Files
//
import { rootReducer } from './reducers';
import Root from './containers/Root/Root'; // Used for HMR

// ==== Redux Store
//
const configureStore = (initialState) => {
  const store = createStore(
      rootReducer,
      initialState,
  );
  // Creating your Redux store

  if (__DEVELOPMENT__ && module.hot) {
    module.hot.accept('./reducers', () => {
      store.replaceReducer(rootReducer);
    });
    // Enable HMR for reducers.
  }

  return store;
};

// ==== Local Variables
//
const initialState = {};
const store = configureStore(initialState);
const history = syncHistoryWithStore(hashHistory, store);
const rootEl = document.getElementById('root');


// ==== Needed for onTouchTap
//      Note: This should only be instantiated once!
//      Reference: https://github.com/zilverline/react-tap-event-plugin
injectTapEventPlugin();


ReactDOM.render(<Root store={store} history={history} />, rootEl);
// ==== Render the application.
//      Note: This is NOT surrounded by AppContainer
//            It will be when the module hot-reloads.

if (__DEVELOPMENT__ && module.hot) {
  module.hot.accept([
    './containers/Root/Root', // Same path as imported above
  ], () => {
    ReactDOM.render(
      <AppContainer>
        <Root store={store} history={history} />
      </AppContainer>,
      rootEl,
    );
  });
}
```

routes.js
```
// ==== Node Modules
//
import React from 'react';
import { IndexRoute, Route } from 'react-router';

// ==== Local Files
//
import { About, Home, Layout } from 'containers';

const routes = (
  <Route path="/" component={Layout}>
    <IndexRoute path="" component={Home} />
    <Route path="/about" component={About} />
  </Route>
);
// ==== Routes must be exported in order for HMR to work.

export default routes;
```


If you would want, you can reference my [GitHub repo](https://github.com/jmahc/boilerplate-react-redux-router-hmr) which contains updated react-hot-loader, webpack 2, HMR, react, react-router, and redux.  All on separate branches.  I would love some help!

**Comment by bochen2014** [comment]
@jmahc  my understanding of how `react-hot-loader` is like this
1. you change your component source code, webpack HMR emit a new file and send to client/browser
2. `react-hot-loader` gets notified by `hmr` and attempts to re-render the changed component 
the tricky part is which component(s) to re-render? all it has is a change file name.
I haven't checked `react-hot-loader` source code (which I should ) but I believe that Dan took the easy approach and renders the entire component tree. That's why Router gets re-rendered and hence we are getting the warning....

I noticed you example is in webpack 2. I don't know if webpack 2 has done some further optimisation to make hot-reload more efficient. . It would be great if you can share how your solution solve the problem

**Comment by jmahc** [comment]
@bochen2014 Sure thing! I'll have it up by this evening (December 11, 2016 @ 11 PM CST) at http://blog.mcardle.tech/

Please let me know any specific questions and I will do my best to help out.

Hope you're having a great weekend!

**Comment by adrianmcli** [comment]
I'm not even sure what I did, but splitting everything up (like what @jmahc did above) solved the issue for me.

The entry point was a huge file with 40 lines of import statements alone before I made this refactor. If anyone is curious as to whether or not it's worth it. DO IT!

**Comment by jmahc** [comment]
@adrianmcli Can you show me the before and after commits (pre-HMR working & now that it's working)?  I would love to know for my own personal reasons!

Not sure how to PM but if you view my GitHub bio., I have a website that contains my contact information.

**Summary**: With HMR, they don't _think_ it be like it is but it _do_.

**Comment by adrianmcli** [comment]
@jmahc unfortunately, it's closed-source work for a client. But I've made some edits to my original post above to illustrate how I split things up! Thanks again for your inspiration!

**Comment by jmahc** [comment]
Cool beans!  I'm just happy you got it working - it has been a monster of a task but by our powers combined...


![Image of Captain Planet](http://movieebuff.com/wp-content/uploads/2016/10/captain.jpg)

**Comment by adrianmcli** [comment]
@wonbyte I actually don't use the AppContainer component at all. I'm still unsure as to what its purpose is.

**Comment by wonbyte** [comment]
@adrianmcli so you just do this?

```
if (module.hot) {
    module.hot.accept('./containers/Root', () => {
        const NewRoot = require('./containers/Root').default;
        render(
                <NewRoot store={store} history={history} />
            document.getElementById('root')
        );
    });
}
```

instead of

```
if (module.hot) {
    module.hot.accept('./containers/Root', () => {
        const NewRoot = require('./containers/Root').default;
        render(
            <AppContainer>
                <NewRoot store={store} history={history} />
            </AppContainer>,
            document.getElementById('root')
        );
    });
}
```

**Comment by adrianmcli** [comment]
@wonbyte I haven't found the need to use `module.hot` at all since I am using react-hot-loader.

Take a look at this React Casts video: https://www.youtube.com/watch?v=f-ctxG2qEps

They demonstrate two ways of doing hot module replacement:

1. Basic HMR implementation with `module.hot`.
2. Using React Hot Reload to skip having to do any of that, and have the added benefit of preserving local component state.

Definitely worth a watch, even if you're not using create-react-app.

**Comment by wonbyte** [comment]
@adrianmcli Interesting. So there is no reason to use module.hot at all...  I wonder if enabling the 'hot' flag on webpack dev server means I don't even have to use the react-hot test line...

so 

```
new WebpackDevServer(webpack(config), {
    hot: true,
}
```

means I don't need

```
test: /\.js?$/,
                exclude: /node_modules/,
                loader: 'react-hot'
```

**Comment by wonbyte** [comment]
@adrianmcli Thanks, that simplifies things a ton. But looking at the https://github.com/gaearon/react-hot-loader/blob/next/src/AppContainer.dev.js it seems like AppContainer is still used in react-hot-loader 3.

**Comment by adrianmcli** [comment]
@wonbyte I'm not using version 3 of React Hot Loader. I'm using the latest stable version from NPM, which is 1.3.1.

Version 3 has been "on the horizon" for almost a year now. I'm not holding my breath until they come out with an actual npm release.

What I would recommend is that you try to get everything working with 1.3.1 (the latest stable version). And then incrementally migrate to 3.0 with the supplied guide.

**Comment by satyadeeproat** [comment]
How to pass props to route. I am doing this but still getting the error

```
const routeConfig = (type) => {
  console.log("at route", type)
  return (      
  <Route>
  <Route path='/' component={Template}>
    <Route path='/pageform(/:id)' component={PageForm} />
  </Route>
  
  <Route path='/:pageSlug' component={Page} slug=type/>
  </Route>
);
}
class App extends React.Component {
  render() {
    const slug = this.props
    console.log("at app", slug)

    return (
      <MuiThemeProvider muiTheme={getMuiTheme()}>
        <Provider store={store}>
          <Router history={browserHistory} routes={routeConfig(slug)} />
        </Provider>
      </MuiThemeProvider>
    );
  };
};
```

**Comment by mocheng** [comment]
Same issue hits me. @dceddia 's solution saved my day.

**Comment by chotalia** [comment]
adding the `key ` attribute in `<Router>` worked for me.
```
<Router key={Math.random()} history={browserHistory}>
        <Route path='/' component={LoginComponent} />
        <Route path='/login' component={LoginComponent} />
...
</Router>
```

**Comment by ngocketit** [comment]
Thanks @chotalia! That works for me.

**Comment by raminious** [comment]
@chotalia your solution is not good and has side effect, obviously it changes all components states to their default states.

**Comment by lumberj** [comment]
Adding a `shouldComponentUpdate` to my Routes component works for me.

```js
class Routes extends Component {
  shouldComponentUpdate () {
    return false
  }

  render () {
    return (
      <Router>
      //....
      </Router>
    )
  }
}
```

Then rendering that in my Root component

**Comment by lumberj** [comment]
@heldrida the entire thing looks something like this: (leaving out details like setting up history and the redux store)


```js
// App.jsx


const App = ({children}) => (
  <div className='app-container'>
     {children}
  </div>
)

class Routes extends Component {
  shouldComponentUpdate () {
    return false
  }

  render () {
    return (
      <Router history={this.props.history}>
        <Route path='/' component={App}>
          <IndexRoute component={App} />
        </Route>
      </Router>
    )
  }
}

class Root extends Component {
  render () {
    const {store, history} = this.props
    return (
      <Provider store={store}>
        <Routes history={history} />
      </Provider>
    )
  }
}
```

```js
// index.jsx
import { AppContainer } from 'react-hot-loader'

ReactDOM.render(
  <AppContainer>
    <App store={store} history={history} />
  </AppContainer>,
  document.getElementById('root')
)

// Hot Module Replacement API
if (module.hot) {
  module.hot.accept('./App', () => {
    const NextApp = require('./App').default
    ReactDOM.render(
      <AppContainer>
        <NextApp store={store} history={history} />
      </AppContainer>,
      document.getElementById('root')
    )
  })
}

**Comment by sandrinodimattia** [comment]
Here's what worked for me:

```js
// Render the application.
render(
  <Provider store={store}>
    {router(history)}
  </Provider>,
  document.getElementById('app')
);

// Support for hot reloading.
if (module.hot) {
  import('react-hot-loader').then(({ AppContainer }) => {
    module.hot.accept('./router', () => {
      import('./router')
      .then((routerModule) => {
        render(
          <AppContainer>
            <Provider store={store}>
              {routerModule.default(history)}
            </Provider>
          </AppContainer>,
          document.getElementById('app')
        );
      });
    });
  });
}
```

**Comment by arshmakker** [comment]
@lumberj Thanks man, this worked for me too. Wonder what's the logic behind this?

**Comment by haim-rubin** [comment]
,*

**Comment by PavelPolyakov** [comment]
Here is the solution which worked in my case:
```javascript
import * as React from "react";
import ReactDOM from "react-dom";
import App from "./App";
import {AppContainer} from 'react-hot-loader';

import createHistory from "history/createBrowserHistory";
const history = createHistory();

const root = document.getElementById('root');

const render = (Component, props = {}) => {
    ReactDOM.render(
        <AppContainer>
            <Component {...props}/>
        </AppContainer>,
        root
    );
}

render(App, { history });

// Hot Module Replacement API
if (module.hot) {
    module.hot.accept('./App', () => {
        render(App, { history });
    });
}
```

How it was before:
```javascript
import * as React from "react";
import ReactDOM from "react-dom";
import App from "./App";
import {AppContainer} from 'react-hot-loader';

const render = (Component, props = {}) => {
    ReactDOM.render(
        <AppContainer>
            <Component/>
        </AppContainer>,
        document.getElementById('root')
    );
}

render(App);

// Hot Module Replacement API
if (module.hot) {
    module.hot.accept('./App', () => {
        render(App);
    });
}
```

And the error:
![image](https://cloud.githubusercontent.com/assets/839290/24555831/cd861484-1632-11e7-8d2c-dcf87cf32f38.png)

However, as you see - main thing is to put history declaration out of the `App` component.
I don't find it very neat, as according to my view these property should be declared in the `App` component itself.

As this repository is moving into the main `react-router` one, I think it would be very helpful to add some official the solution into the `react-router` FAQ.

**Comment by sliultron** [comment]
Hi, @PavelPolyakov i found an interesting problem with the working code you provided. if i add react-hot-loader/babel plugin in .babelrc as the [documentation](https://webpack.js.org/guides/hmr-react/ ) shows 
 ```
   "plugins": [
    "react-hot-loader/babel"
    // Enables React code to work with HMR.
  ]
```

then, i will still see the warning message.  i am using "react-hot-loader@v3.0.0-beta.6".  The warning message goes away when removing that plugin. Can anyone help to explain why?

Thanks

**Comment by yangfan0095** [comment]
I  also encountered this problem in my project , but I find my  react-router vision is 2.xxx , then I browsed the   docs  Migrating from v2/v3 to v4  ,  and I migrating the version to 4.x , this problem never happen .

https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/guides/migrating.md

it shows :
In v3, the <Route> was not really a component. Instead, all of your application's <Route> elements were just used to created a route configuration object.
With v4, you layout your app's components just like a regular React application. Anywhere that you want to render content based on the location (specifically, its pathname), you render a <Route>.

The v4 <Route> component is actually a component. so wherever you render a <Route> component, content will be rendered. When the <Route>'s path matches the current location, it will use its rendering prop (component, render, or children) to render. When the <Route>'s path does not match, it will render null.

**Comment by shidaping** [comment]
call ReactDOM.unmountComponentAtNode. it will work!
` js
ReactDOM.render((
  <Provider store={store}>
    <Router routes={routes} history={history} />
  </Provider>
), document.getElementById('app'));

if (module.hot) {
  module.hot.accept('./routes', () => {
    ReactDOM.unmountComponentAtNode(document.getElementById('app'));
    const nextRoutes = require('./routes').default;
    ReactDOM.render(
      <Provider store={store}>
        <Router routes={nextRoutes} history={history} />
      </Provider>,
      document.getElementById('app'),
    );
  });
}
`
