### ISSUE TITLE
onEnter / onLeave called multiple times

### ISSUE THREAD

**Issue by bkniffler** [rackt/redux-simple-router#186]
Hey, 
If I'm using a react-router `<Link/>`, onEnter and onLeave hooks are sometimes called twice.
It must have something to do with the `history.listen`, as if I comment out
```jsx
} else if (!locationsAreEqual(getRouterState(), route)) {
// lines 170-171
// var method = location.action === 'REPLACE' ? replacePath : pushPath;
// store.dispatch(method(route.path, route.state, { avoidRouterUpdate: true }));
}
```
it works as it should, with only a single call.

Is this a bug?

**Comment by jlongster** [comment]
We're about to release 2.0.0 (tomorrow) as master has quite different code. Can you try `redux-simple-router@next`?

**Comment by bkniffler** [comment]
Tanks for the quick reply. 

I set up the redux-simple-router as in the docs:
```
var middleware = reduxSimpleRouter.syncHistory(history);
middleware.syncHistoryToStore(store);
```
These lines are causing problems, the initialLocation is undefined, which causes history to throw an error.
```jsx
// If we're resetting to the beginning, use the saved initial value. We
// need to dispatch a new action at this point to populate the store
// appropriately.

if (!location) {
    history.transitionTo(initialLocation);
    return;
}
```

**Comment by bkniffler** [comment]
This solves the problem, thanks!
