### ISSUE TITLE
syncHistoryToStore makes createHistory throw an error 

### ISSUE THREAD

**Issue by georgesboris** [rackt/redux-simple-router#189]
Just tried to upgrade to the current source as the npm one is not working.
I've reset my configurations based on the new docs. But now I'm getting this error:

```
createHistory.js?cf40:39
Uncaught TypeError: Cannot read property 'pathname' of undefined
```
this error is being thrown here:
```
function locationsAreEqual(a, b) {
  return a.pathname === b.pathname && a.search === b.search &&
  //a.action === b.action && // Different action !== location change.
  a.key === b.key && _deepEqual2['default'](a.state, b.state);
}
```

but if I omit the `reduxRouterMiddleware.syncHistoryToStore(store);`
no error is thrown (but the router does not work).

**Comment by timdorr** [comment]
`syncHistoryToStore` is only needed if you're using Redux Dev Tools. If not, you can omit it. We should make the docs more clear about this, though.

**Comment by jlongster** [comment]
`locationsAreEqual` does not exist in the latest code, so you probably don't have things installed correctly.

@timdorr Not a bad point. We can add it somewhere, but people should still call it so whenever they try the devtools it "just works".

**Comment by jlongster** [comment]
I'm releasing 2.0.0 right now, and this code does not exist in there.

**Comment by jlongster** [comment]
@timdorr In fact, I think I'm just going to rename that method. I didn't realize that it was 100% just for replays. I'm going to rename it to `listenForReplays`. I'd like to go ahead and push 2.0.1 out though.... Anyone happen to see this and have thoughts on that?

**Comment by jlongster** [comment]
https://github.com/rackt/redux-simple-router/pull/191
