### ISSUE TITLE
syncHistory is not a function

### ISSUE THREAD

**Issue by ferllings** [rackt/redux-simple-router#192]
Hello

I have this error on version 1.0.2 when importing the syncHistory function
```
Uncaught TypeError: (0 , _reduxSimpleRouter.syncHistory) is not a function
```

The line number directly point to 
```
import { syncHistory, routeReducer } from 'redux-simple-router'
```

Any idea what I'm doing wrong?

**Comment by jlongster** [comment]
The docs are currently for an unreleased version (there is a note about that), you need to look at the [1.0.2](https://github.com/rackt/redux-simple-router/tree/1.0.2#api) docs. We're about to release 2.0.1.

**Comment by ferllings** [comment]
Right, sorry about that
