### ISSUE TITLE
This is daunting.. comments please?

### ISSUE THREAD

**Issue by cameronjroe** [rackt/redux-simple-router#194]
I'm pretty new to redux and react-router.. looking at the example makes my stomach nauseous. Any chance you could at least put comments breaking down what's happening. I think I get it now, but I had to stare at it for 30 minutes. 

Also, the API, docs on readme, and example are not in sync. Would be ideal to have those similar examples.

**Comment by jlongster** [comment]
Please don't use such a strong tone. We aren't here to document redux or react-router, we assume you already know both of those. If you are already familiar with those this should be no problem at all.

**Comment by cameronjroe** [comment]
Didn't mean to come off so strong, but I want to be transparent it's a little sloppy. This would be for the benefit of everyone reading these docs. I'll even do a PR if it's such a big deal. Sorry man. Just trying to ramp up quickly with it.
