### ISSUE TITLE
How to change history from inside a reducer

### ISSUE THREAD

**Issue by gfpacheco** [rackt/redux-simple-router#195]
My app starts at `/`, and the first thing I do is fetch some data: an array of objects.

There should be always one object selected, and that selection should be reflected to the url: `/objectId`.

My first thought was to change the path on my reducer that handles the data response, calling `history.push('/' + objects[0].id)`.

But `redux-simple-router` is always listening to the history and dispatching actions each time it changes. Which is an action being dispatched from inside a reducer (and it shouldn't happen!).

Is it possible to change the location and not trigger an action?

**Comment by gfpacheco** [comment]
It's just a test, the variable and functions names aren't good, but it worked for me: https://github.com/gfpacheco/redux-simple-router/commit/4b3c74df06df47e9fe86df1ca4c11c52d78c1aed

**Comment by mjrussell** [comment]
You should never do any side effects (such as changing the url) inside of a reducer, see this section of the redux docs: https://github.com/rackt/redux/blob/master/docs/basics/Reducers.md#handling-actions

As for your specific use case, you could handle it a number of (safe) ways.

1. Use redux-thunk or redux-promise to chain your fetch. On successful data retrieval, dispatch an a `pushState` or `replaceState` from routeActions to update the URL param to the object you want selected.

2. Use a componentWillMount/componentWillReceiveProps inside of your connected component that React-Router renders for the given path to check that an item is selected. If either no URL param for `objectId` is specified or its invalid, dispatch the `pushState` or `replaceState` to the `objectId` you want.

**Comment by gfpacheco** [comment]
I didn't think of changing the url as a side effect, actually I thought it was the right place to do it, since the reducer is the one responsible for changing the app state in response to an action, but ok, I'll take it.

I'm already using `redux-thunk`, my problem was that `componentDidMount` is called only once and I needed dispatch `loadObjects` the first time and call `selectObject` the next time.

I didn't know about `componentWillReceiveProps`, it worked fine for me, thanks a lot!
