### ISSUE TITLE
It appears you have provided a deprecated history object to `<Router/>`

### ISSUE THREAD

**Issue by gabrielenosso** [rackt/redux-simple-router#196]
Using the code in the tutorial as it is results in receiving a Warning by react-router:

It appears you have provided a deprecated history object to `<Router/>`, please use a history provided by React Router with `import { browserHistory } from 'react-router'` or `import { hashHistory } from 'react-router'`. If you are using a custom history please create it with `useRouterHistory`, see http://tiny.cc/router-usinghistory for details.

As you can see from this link, https://github.com/rackt/react-router/blob/master/upgrade-guides/v2.0.0.md#using-custom-histories, the creation of the history should change in:

import { useRouterHistory } from 'react-router';
const history = useRouterHistory(createHistory)({ queryKey: false });

**Comment by timdorr** [comment]
You're right! Would you mind submitting a PR to fix this?
