### ISSUE TITLE
v2.x sync redux and router messes up the store

### ISSUE THREAD

**Issue by rdsubhas** [rackt/redux-simple-router#199]
Hi, Firstly thanks for the great library! I'm a bit confused by the 2.x changes which seem to look a step backward from 1.x.

* In v1.x - the usual redux way of `createStore` needed **no DOM reference**
* In v2.x - we have to add a routeMiddleware to store, which in turn needs a history first, so we have to import `createHashHistory` or `createBrowserHistory`, thus referencing DOM. So I can't create a plain JS store anymore.

The highlight of Redux was **plain JS** for most stuff - actions, reducers, store. With this one change in this library, that feature seems break. It has implications in tests.

Wouldn't it have been nice if this was a HOS instead of a middleware? Then I could have used the plain store for tests, and wrap it up in a HOS when rendering the app.

Am I missing anything obvious or making a mistake? Is there a way to make the store plain JS even with the current v2.x version? Some documentation or help would be really valuable. Thanks!

**Comment by timdorr** [comment]
In 1.x, you had to `syncReduxAndRouter`, which requires a `history` instance. This hasn't changed in 2.x, it's just moved to a middleware function and doesn't require a store instance.

If you ned a DOM-less history, just use a memory history.

**Comment by rdsubhas** [comment]
* syncReduxAndRouter happens **after** the store is created
* Middleware needs to be inserted **before** a store is created

@timdorr You are saying that **middleware doesn't require a store**. But please focus:

> Store now requires a middleware which in turn requires DOM

i.e. **Store indirectly now needs a DOM**. For testing, this means I have to create a stub middleware. Change but bearable. But you know there will soon be support for moving dispatch to web workers, service workers, etc. Are you sure having a middleware that accesses DOM, and thus a Store (+indirectly reducers) that depends on DOM will play well with the Redux ecosystem?

**Comment by timdorr** [comment]
Again, if you don't need or want a DOM, use a memory history. Nothing in `redux-simple-router` requires a DOM, it is your history that defines that. And a memory history works without a DOM just fine for server environments.

**Comment by rdsubhas** [comment]
@timdorr I'm not saying I **want** a memory history. I'm saying I'm being **forced** to use a memory history. There's a difference. I'm now having to patch up the store separately for server and separately for client. This was not the case with v1.x - where I had access to a pure JS store.

**Comment by rdsubhas** [comment]
Its really obvious that `redux-simple-router` does not *directly* require DOM. It requires history. In v1.x, the Standard way (i.e. following `README.md`) did not mess up with the plain JS store. In v2.x, following `README.md` **does** mess up the plain JS store. Is that point really not that obvious?

**Comment by timdorr** [comment]
Just create a function to configure your store that passes in the history instance you want to use.
```js
function configureStore(history, initialState = {}) {
  let middleware = [
    syncHistory(history),
    someMiddleware,
    otherMiddleware
  ];

  const createStoreWithMiddleware = applyMiddleware(...middleware)(createStore);
  return createStoreWithMiddleware(rootReducer, initialState);
}
```
This is a very common pattern in Redux, as you want to configure your middleware (and set up hot reloading) in one place, not duplicating the setup for your client and server.

**Comment by rdsubhas** [comment]
@timdorr thanks for that simple solution. Sorry I got a bit frustrated.

But one last thing please: This will help with testing. But when running in a browser, the store will have a real history and thus real DOM reference inside. How do you think this will impact web worker / service worker functionalities that we hope Redux will soon have?

**Comment by timdorr** [comment]
Redux doesn't need anything for web worker support (it's not anything we're planning on adding, at least). You can add that with middleware: just intercept all dispatches and redirect to your worker via a message. 

The store doesn't contain DOM references. We only put a location descriptor back in via the reducer, which is a POJO containing info about the current location. That's it. Browser and hash history talk to `window`, but there is no reference that we track that's tied back to a DOM element. It's all just strings and numbers.

**Comment by rdsubhas** [comment]
Yep, Store is strings and numbers and middleware, this one with history, which in turn talks to window, and I thought `window` was a DOM element. Essentially store tracking back to window. The 2.x change makes me uneasy, somehow a HOS sounds less problem, but I'll trust your decisions.
