### ISSUE TITLE
Current support for react router 2.0?

### ISSUE THREAD

**Issue by tyleriguchi** [rackt/redux-simple-router#211]
I'm using `"redux-simple-router": "^2.0.3"` and `"react-router": "^2.0.0-rc5",` and am having difficulty getting react router to update the view that's being rendered.

````
import { routeActions } from 'redux-simple-router'

@connect( state => state)
export default class Beer extends Component {
  render() {
    const { dispatch, beer } = this.props;

    return (
      <li>
        <button onClick={ () => dispatch(routeActions.push(`/beers/${beer.id}`))}>test</button>
      </li>
    )
  }
}
````

Things are being pushed into the history, but the view doesn't refresh. Is this an implementation issue or dependency issue?

**Comment by timdorr** [comment]
Router doesn't replace the component if you navigate to the same place in the route tree. It only provides new props. You will have to make sure you're handling this right on your end.

**Comment by tyleriguchi** [comment]
@timdorr Thanks for pointing me in the right direction, I appreciate it :+1:

**Comment by damassi** [comment]
@timdorr could you elaborate a bit? I just upgraded from react-simple-router today and am having trouble tracking down the trouble in my app. It seems like somewhere in the chain something is not firing, and this might be it. Is this behavior different than 1.0?
