### ISSUE TITLE
Getting next component for async props loading?

### ISSUE THREAD

**Issue by Keats** [rackt/redux-simple-router#214]
I started migrating  from redux-router to redux-simple-router and there's one thing that I'm not sure whether it's supported:
In redux-router, the ROUTER_DID_CHANGE action has a `components` and `params` attributes, which I use in a middleware to preload data (components can have a `fetchData` method that takes the params and dispatch) and the middlewares waits until the promise is done to render to continue the chain.

Afaik, this package doesn't give the components or the params (which I guess can easily be added here).
I've seen async-props but the author himself says that it is half-baked and should not be used, so how do people do their blocking async loading? I could make a dict mapping urls to components but that feels like a hack.

Edit: I don't care about server-side rendering if that's of any difference

**Comment by timdorr** [comment]
async-props isn't half-baked, just not yet at 1.0. It's one way of handling your data loading that is totally valid and will get better over time. 

You can use getComponent in react-router, which is async,  to run code on the component before loading. Just read a static function on it before providing it back to the router callback. 

One thing to keep in mind is if you block on loading a component, your app is going to hang on every click without a visual loading indicator. That's going to have a negative effect on your UX. I would just handle this with componentWillMount and making sure your component can render a loading state while waiting for data.

**Comment by Keats** [comment]
Thanks, missed the getComponent fn

`componentWillMount` doesn't have access to the params that are needed for calls afaik, could use the ctor though

(for reference the half-baked came from https://github.com/rackt/async-props/issues/46)

**Comment by timdorr** [comment]
ComponentWillMount should have access to props, which should have everything you need.

**Comment by Keats** [comment]
Ah yeah sorry was looking at the params, forgot I have this.
Thanks again!
