### ISSUE TITLE
Using action creators doesn't trigger url request

### ISSUE THREAD

**Issue by startupthekid** [rackt/redux-simple-router#216]
If I do `routeActions.push({ pathname: '/', state: 'some_state' })`, I would expect it to fire a request for `/` and then on the server I could handle route matching using `react-router`. However no network request is fired, it just updates the redux store.

This is especially critical in applications that do server side rendering because they need to be able to capture state and pathname, among on things, on the server. And if no request is made, nothing happens.

**Comment by timdorr** [comment]
I'm not sure I understand. This is exactly what `react-router` and this library are for. 

Doing a `push` is an in-place navigation, meaning it doesn't navigate you to another actual page. It wraps around `history.pushState` in the browser context (or hash changes if that's how you have it configured), which updates the browser URL and lets you keep your app loaded while navigating around it. 

If you want to invoke a full page navigation, you would need to `window.location = '/'`. That will blow away your app and start over fresh in the browser. The server can do its thing and you're ready to get started again.
