### ISSUE TITLE
broswerHistory not valid react-router property

### ISSUE THREAD

**Issue by aray12** [rackt/redux-simple-router#217]
In the README.md it states you need to pass the browserHistory to the middleware so that redux will be aware of the state. 
```javascript
import { Router, Route, browserHistory } from 'react-router'
```

I cannot find any reference to browserHistory in docs or source. Can I grab the appropriate property from the `rackt/history`?

**Comment by mjrussell** [comment]
@aray12 most likely you are on React-Router v1 and not v2. This library supports both and you should be able to use any history from `rackt/history` without any issues, but must make sure you pass the created history also to React-Router's `<Router>`

**Comment by aray12** [comment]
@mjrussell thanks for the quick response. The confusion was because the latest tag on react-router on github still points to 1.0.3

**Comment by chibicode** [comment]
I also got confused too, but I think you can make 1.0.3 work like this:
https://github.com/rackt/redux-simple-router/blob/00551dbac88e87ec7c76610008d4d90a9bbf17cc/examples/basic/app.js#L16-L17
