### ISSUE TITLE
Rewrite example to use ES6 style modules

### ISSUE THREAD

**Issue by venil7** [rackt/redux-simple-router#221]
Why do examples files, eg. `redux-simple-router/examples/basic/app.js`
contains both `ES6` and `CommonJS` style modules? 

is there any particular reason to use `CommonJS` modules? and if so can t be explained, otherwise rewrite examples to only use `ES6`

**Comment by timdorr** [comment]
Looks like some of it got added in #167. I'm not sure why they were ever CommonJS. 

I'd love a PR to rewrite those modules to ES6 modules! :smile:

**Comment by venil7** [comment]
Great, I renamed issue for clarity,
I might submit PR later, if nobody else does
