### ISSUE TITLE
Sending location object twice

### ISSUE THREAD

**Issue by Aweary** [rackt/redux-simple-router#223]
https://github.com/rackt/redux-simple-router/blob/master/src/index.js#L41
```js
export function routeReducer(state = initialState, { type, payload: location }) {
  if (type !== UPDATE_LOCATION) {
    return state
  }

  return { ...state, location }
}
```

Is there a reason that `location` is being returned as a top level property here? If we're already spreading `state`, we should get the same data in `payload`, so it seems like we're sending the same data twice.

**Comment by timdorr** [comment]
I'm not sure I follow. How are we sending it twice?

We swallow `TRANSITION` actions in the middleware and only dispatch an `UPDATE_LOCATION` action from our history listener, so the reducer is only called once. The spread is so we're merging in the previous state, not overwriting it with *only* the `location`.

**Comment by Aweary** [comment]
Sorry, my mistake, misread `routeReducer`.
