### ISSUE TITLE
Checking whether goBack results in a valid location

### ISSUE THREAD

**Issue by romseguy** [rackt/redux-simple-router#224]
If I open a new browser tab and open the app at some `/route` and make the router dispatch `routeActions.goBack()` it goes back to the "browser tab home page", how to make sure it goes to `/` instead?

**Comment by timdorr** [comment]
This is just wrapping around the native `go(-1)` function. This is more of a question for `history`, since we don't keep a historic record of your location state, just whatever is current.

**Comment by romseguy** [comment]
Fair enough, found some clues https://github.com/rackt/history/issues/195
