### ISSUE TITLE
routing.location.query missing when action is POP

### ISSUE THREAD

**Issue by hisapy** [rackt/redux-simple-router#230]
Whenever the **location.action** is POP (i.e. when using browser's back button) **location.query** is missing.

This doesn't happen when **location.action** is PUSH. 

Currently I'm creating my own **query** when there is a **location.search**  but no location query.

```javascript
function mapStateToProps(state, ownProps) {
  if ( state.routing.location.search && ! state.routing.location.query ) {
    state.routing.location.query = {
      page: getParameterByName('page', state.routing.location.search)
    }
  }
  /* return props */
}
```

**Comment by timdorr** [comment]
This is a react-router bug that's waiting on a release of history to fix it. You'll either have to wait for the next release or build off of master for react-router and history.

**Comment by hisapy** [comment]
OK and thx @timdorr

**Comment by sompylasar** [comment]
@timdorr Do you know by chance has this been fixed and where? I'm using `"react-router": "^2.0.0-rc5",` and getting a similar issue (not sure if the same issue) - in the route component props, "query" is missing from the server-side "location" but present in the browser-side "location".
