### ISSUE TITLE
Trouble calling dispatch

### ISSUE THREAD

**Issue by pulpfree** [rackt/redux-simple-router#233]
I'm attempting to call the push method in a button similar to your example:

    import React from 'react'
    import { routeActions } from 'redux-simple-router'

    export default function Dashboard({ dispatch }) {
      return <div>
       <button onClick={() => dispatch(routeActions.push('/admin/'))} >my button</button>
      </div>
    }

This results in an error: "Uncaught TypeError: dispatch is not a function." What am I doing wrong?

**Comment by timdorr** [comment]
That's because you're not getting `dispatch` as a prop. That would likely be a react-redux issue. I'm not sure how it handles functional components right now.
